version: "3"
services:
  develop:
    build: .
    container_name: arcgis-proxy-develop
    environment:
      PORT: 35730
      ENVIRONMENT: dev
      DEBUG: "True"
      GATEWAY_URL: http://mymachine:9000
      MICROSERVICE_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU4MjBhZDk0NjlhMDI4Nzk4MmY0Y2QxOCIsInByb3ZpZGVyIjoibG9jYWwiLCJwcm92aWRlcklkIjpudWxsLCJlbWFpbCI6InNlcmdpby5nb3JkaWxsb0B2aXp6dWFsaXR5LmNvbSIsInJvbGUiOiJBRE1JTiIsImNyZWF0ZWRBdCI6IjIwMTYtMTEtMDdUMTY6MzY6MzYuODY4WiIsImV4dHJhVXNlckRhdGEiOnsiYXBwcyI6WyJnZnciLCJwcmVwIiwiYXF1ZWR1Y3QiLCJmb3Jlc3QtYXRsYXMiLCJydyIsImRhdGE0c2RnIl19fQ.3GzuhG8wD4gI5Fo6NTqHC_Dq6ChKPPWXygga2mAuKZw
      LOCAL_URL: http://mymachine:5700
      API_VERSION: v1
      AWS_REGION: "us-east-1"
      REQUIRE_API_KEY: "True"
      AWS_CLOUD_WATCH_LOGGING_ENABLED: "False"
    command: develop
    volumes:
      - ./arcgis_proxy:/opt/arcgis_proxy/arcgis_proxy
    restart: always
