apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: gfw
  labels:
    name: arcgis-proxy
  name: arcgis-proxy
spec:
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        name: arcgis-proxy
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: type
                    operator: In
                    values:
                      - apps
      containers:
        - name: arcgis-proxy
          image: vizzuality/arcgis-proxy
          imagePullPolicy: Always
          resources:
            requests:
              memory: "0Mi"
              cpu: "0m"
          args:
            - start
          env:
            - name: PORT
              value: "5700"
            - name: ENVIRONMENT
              value: staging
            - name: LOCAL_URL
              value: http://arcgis-proxy.gfw.svc.cluster.local:5700
            - name: CT_URL
              valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_URL
            - name: CT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_TOKEN
            - name: CT_REGISTER_MODE
              valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_REGISTER_MODE
            - name: API_VERSION
              valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: API_VERSION

          ports:
            - containerPort: 5700

      restartPolicy: Always
